version: 2
jobs:
  build:
    docker:
      - image: python:3.6.4
    working_directory: ~/adventofcode-2018
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: |
            pip install coverage
            python -m unittest day01_test.py -v
            coverage run day01_test.py -v
            coverage report -m
            python -m unittest day02_test.py -v
            coverage run day02_test.py -v
            coverage report -m
            python -m unittest day03_test.py -v
            coverage run day03_test.py -v
            coverage report -m
            python -m unittest day04_test.py -v
            coverage run day04_test.py -v
            coverage report -m
            python -m unittest day05_test.py -v
            coverage run day05_test.py -v
            coverage report -m
            python -m unittest day06_test.py -v
            coverage run day06_test.py -v
            coverage report -m
            python -m unittest day07_test.py -v
            coverage run day07_test.py -v
            coverage report -m
            python -m unittest day10_test.py -v
            coverage run day10_test.py -v
            coverage report -m
      - run:
          name: "Get the results"
          command: |
            python day01.py inputs/day01.txt
            python day02.py inputs/day02.txt
            python day03.py inputs/day03.txt
            python day04.py inputs/day04.txt
            python day05.py inputs/day05.txt
            python day06.py inputs/day06.txt
            python day07.py inputs/day07.txt
            python day10.py inputs/day10.txt